#!/bin/bash

./download_nasdaq_news.py --output-dir us_stocks_sip/press_json/ NVDA AMD HOOD CEG TSM MSFT SMCI RGTI QUBT AMZN ASML AAPL TXN DASH META ANSS ADI AMAT INTU GOOG PLTR AVGO CDW ON KLAC MDB DDOG QCOM PANW CTSH MSTR APP LRCX CRWD ADBE TSLA CSCO LIN ISRG PEP NFLX COST BKNG AMGN ORLY PYPL MAR NXPI ADSK ABNB BIIB ARM KHC GEHC AZN LULU CTSH EXC FAST CSGP TTD BKR FANG TEAM WDAY ROP CPRT CDNS REGN ORLY CTAS MELI AEP MRVL SBUX GILD

./json2parquet_press.py --input-dir us_stocks_sip/press_json/ --output-dir us_stocks_sip/press

